# Generated by Django 4.2 on 2024-12-04 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
